---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-map
data:
  default.conf: |
    ########################### SERVER BLOCK ####################
    server {
      listen 80;

      location / {
          proxy_pass http://127.0.0.1:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: default
  labels:
    app: naukma-devops
spec:
  selector:
    matchLabels:
      app: nginx-proxy
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      volumes:
        - name: nginx-map
          configMap:
            name: nginx-map
            defaultMode: 484
      containers:
        - name: nginx-proxy
          image: nginx:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-map
              subPath: default.conf
          livenessProbe:
            httpGet:
              path: /
              port: 3000
        - name: node-app
          image: kkpagaev/naukma-devops:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: naukma-devops
spec:
  selector:
    app: nginx-proxy
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
